In [1]:
import tensorflow as tf

In [2]:
'''
Tensor is generalization of vectors and matrices to potentially higher dimensions.
TensorFlow represents tensors as n-dimensional array of base datatypes.
'''

'\nTensor is generalization of vectors and matrices to potentially higher dimensions.\nTensorFlow represents tensors as n-dimensional array of base datatypes.\n'

# Creating Tensors

In [3]:
string = tf.Variable("This is a String" , tf.string)
number = tf.Variable(69 , tf.int16)
floating = tf.Variable(5.0003 , tf.float64)

# Rank/Degree Of Tensors

In [11]:
# Rank/Degree Means NUmber of dimensions involved in tensor.
# for a scalar , rank is 0
# It can also be stated in terms of pythin as highest number of nesting
# what we have done above was example of scalars

rank1_tensor = tf.Variable(["alpha"] , tf.string)
rank2_tensor = tf.Variable([["alpha" , "delta"] , ["beta", "gamma"]] , tf.string)

# rank2_tensor = tf.Variable([["alpha"] , ["beta", "gamma"]] , tf.string) : This will throw Error!!!

In [12]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Shape Of Tensors

In [14]:
# Amount of elements that exists in each direction

rank2_tensor.shape

TensorShape([2, 2])

# Changing Shape

In [18]:
reshaped1 = tf.ones([2,3])

In [25]:
reshaped2 = tf.reshape(reshaped1 , [3,2])
print(reshaped2)

#no. of elements in both tensors, the one to be changed and the changed one should be same

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [31]:
# To flatten a Tensor We Can Do:
zeroed = tf.zeros([5,5,5])
reshaped3 = tf.reshape(zeroed , [125])
reshaped3

<tf.Tensor: shape=(125,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.], dtype=float32)>

In [32]:
# You can automatically specify the reshaped dimension as:
automated = tf.ones([5,5,5,5])
reshaped4 = tf.reshape(automated , [125,-1]) #TensorFlow Will automatically determine what must be the dimension instead of -1
reshaped4

<tf.Tensor: shape=(125, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1.

# Types Of Tensors

In [22]:
'''
Variables
Constants
PlaceHolder
SparseTensor

'''

'\nVariables\nConstants\nPlaceHolder\nSparseTensor\n\n'

# Evaluating Tensors

In [24]:
with tf.Session as sess: #Create A Session Using Default Graph
    tensor.eval() # tensor will of course be name of your tensor

AttributeError: module 'tensorflow' has no attribute 'Session'